version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: osint-postgres
    environment:
      POSTGRES_USER: osint
      POSTGRES_PASSWORD: osint_dev_password
      POSTGRES_DB: osint_archive
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U osint -d osint_archive"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - osint-network

  minio:
    image: minio/minio:latest
    container_name: osint-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - osint-network

  redis:
    image: redis:7-alpine
    container_name: osint-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - osint-network

volumes:
  postgres_data:
    name: osint_postgres_data
  minio_data:
    name: osint_minio_data
  redis_data:
    name: osint_redis_data

networks:
  osint-network:
    name: osint-network
    driver: bridge
