"""Add unique constraint on archive_id and message_id

Revision ID: a9cb3331fe33
Revises: 15e9cd5477d0
Create Date: 2025-10-25 08:59:27.893288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9cb3331fe33'
down_revision: Union[str, Sequence[str], None] = '15e9cd5477d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_messages_archive_message', 'messages', ['archive_id', 'message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_messages_archive_message', 'messages', type_='unique')
    # ### end Alembic commands ###
